In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("techlayoffs.csv")

In [3]:
df

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,...,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,...,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,...,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,...,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,...,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,T11995,Anthropic,Gaming,USA,Enterprise,Mar,2024,766,8.4,Market Slowdown,...,Moderate Hiring,15.8,Software Engineer,18.5,-16.8,-0.8,4.0,6.7,5.1,Bull Market
11996,T11996,Intel,Cybersecurity,Canada,Mid-size,Jul,2026,3407,13.9,Restructuring,...,Hiring Freeze,51.8,Cloud Engineer,75.3,9.7,-1.7,2.3,7.7,6.2,Stable
11997,T11997,Netflix,Social Media,USA,Big Tech,Sep,2025,2576,8.7,Market Slowdown,...,Moderate Hiring,88.8,DevOps Engineer,40.9,11.1,10.7,7.0,8.0,5.1,Recession
11998,T11998,Salesforce,Gaming,Germany,Big Tech,Sep,2025,1039,9.1,Overhiring Correction,...,Moderate Hiring,37.6,Cybersecurity Analyst,24.2,44.2,27.4,8.9,7.3,6.2,Bull Market
11999,T11999,Databricks,AI,Germany,Big Tech,Mar,2026,493,6.6,Restructuring,...,Moderate Hiring,32.6,ML Engineer,45.1,-9.3,-7.2,2.9,4.9,6.0,Bull Market

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   record_id               12000 non-null  str
 1   company_name            12000 non-null  str
 2   industry                12000 non-null  str
 3   country                 12000 non-null  str
 4   company_size            12000 non-null  str
 5   month                   12000 non-null  str
 6   year                    12000 non-null  int64
 7   layoffs_count           12000 non-null  int64
 8   layoff_percentage       12000 non-null  float64
 9   reason_for_layoffs      12000 non-null  str
 10  ai_automation_impact    12000 non-null  float64
 11  ai_replacement_risk     12000 non-null  float64
 12  open_roles              12000 non-null  int64
 13  hiring_trend            12000 non-null  str
 14  remote_jobs_percentage  12000 non-null  float64
 15  top_hiring_role         12000 non-null  str
 16  stock_growth_percent    12000 non-null  float64
 17  revenue_growth_percent  12000 non-null  float64
 18  salary_budget_change    12000 non-null  float64
 19  ai_adoption_level       12000 non-null  float64
 20  employee_sentiment      12000 non-null  float64
 21  job_security_score      12000 non-null  float64
 22  market_condition        12000 non-null  str
dtypes: float64(10), int64(3), str(10)
memory usage: 3.1 MB

In [5]:
df.describe()

,year,layoffs_count,layoff_percentage,ai_automation_impact,ai_replacement_risk,open_roles,remote_jobs_percentage,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,2024.998750,5009.572083,12.780125,6.376983,7.208758,2884.395000,50.205150,22.466550,17.469175,5.920392,5.538750,6.496217,5.805033
std,0.817703,5159.360491,10.212612,3.544012,2.677148,2149.615907,23.299575,38.814405,24.359448,11.777264,2.583047,1.582356,1.649677
min,2024.000000,0.000000,0.000000,0.600000,1.000000,52.000000,10.000000,-45.000000,-25.000000,-28.000000,1.000000,1.300000,1.000000
25%,2024.000000,1369.500000,5.100000,3.500000,5.100000,1151.000000,29.800000,-11.200000,-3.500000,-2.700000,3.300000,5.400000,4.700000
50%,2025.000000,2733.000000,9.400000,5.900000,7.600000,2282.000000,50.500000,22.600000,17.500000,5.900000,5.600000,6.500000,5.900000
75%,2026.000000,6490.000000,17.300000,8.800000,10.000000,4432.250000,70.700000,55.700000,38.400000,14.600000,7.700000,7.600000,7.000000
max,2026.000000,19999.000000,40.000000,16.800000,10.000000,9997.000000,90.000000,90.000000,60.000000,38.200000,10.000000,10.000000,10.000000

In [6]:
df.isna().sum()

record_id                 0
company_name              0
industry                  0
country                   0
company_size              0
month                     0
year                      0
layoffs_count             0
layoff_percentage         0
reason_for_layoffs        0
ai_automation_impact      0
ai_replacement_risk       0
open_roles                0
hiring_trend              0
remote_jobs_percentage    0
top_hiring_role           0
stock_growth_percent      0
revenue_growth_percent    0
salary_budget_change      0
ai_adoption_level         0
employee_sentiment        0
job_security_score        0
market_condition          0
dtype: int64

KeyError: 'Stock growth percent'